services:

    snow.systempay:
        class: Snow\SystempayBundle\Service\SystemPay
        arguments: [@service_container]

    snow.systempay.twig_extension:
        class: Snow\SystempayBundle\Twig\TwigExtension
        tags:
            - { name: twig.extension }